### ISSUE TITLE
yarn dev 启动 报错: Failed to resolve import "D:myCodeislanddocsindex.md" from "virtual:routes". Does the file exist?

### ISSUE THREAD

**Issue by Davont** [sanyuan0704/island.js#30]
### Describe the bug

根据 [文档](https://island.sanyuan0704.top/guide/getting-started.html) 案例 操作过来 ，最后 yarn dev 启动失败

### Reproduction

```js
[plugin:vite:import-analysis] Failed to resolve import "D:myCodeislanddocsindex.md" from "virtual:routes". Does the file exist?
32 |  ;
33 |  import React from 'react';
34 |  const Route0 = lazyWithPreload(() => import('D:\myCode\island\docs\index.md'))
   |                                              ^
35 |  export const routes = [
36 |  { path: '/', element: React.createElement(Route0), filePath: 'D:\myCode\island\docs\index.md', preload: Route0.preload }
    at formatError (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35330:46)
    at TransformContext.error (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35326:19)
    at normalizeUrl (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40255:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransformContext.transform (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
    at async Object.transform (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:30)
    at async loadAndTransform (file:///D:/myCode/island/node_modules/islandjs/node_modules/vite/dist/node/chunks
```

![image](https://user-images.githubusercontent.com/28757633/191729808-eaab7985-5c94-47f4-8b20-0e55f6e2177d.png)

![image](https://user-images.githubusercontent.com/28757633/191730287-e5f42ddf-0474-496b-875d-ebcf9606c74b.png)

### Expected behavior

希望能正常跑通 流程。

### System Info

```Shell
windows 系统
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by sanyuan0704** [comment]
请问是用的哪个 islandjs 版本？

**Comment by Davont** [comment]
> 请问是用的哪个 islandjs 版本？

0.1.5

**Comment by sanyuan0704** [comment]
这个 PR 解决了 https://github.com/sanyuan0704/island.js/pull/31

**Comment by sanyuan0704** [comment]
0.1.6 版本应该没有这个问题了
