### ISSUE TITLE
e2e test run failed

### ISSUE THREAD

**Issue by liuqh0609** [sanyuan0704/island.js#69]
### Describe the bug

e2e test run failed.
I think it's because the directory it's running in is incorrect
```shell
Error: Command failed with exit code 1: npm i --registry=https://registry.npmmirror.com/
    at null.makeError (/Users/liuqinghua/lqh/island.js/node_modules/.pnpm/execa@6.1.0/node_modules/execa/lib/error.js:59:11)
    at execaSync (/Users/liuqinghua/lqh/island.js/node_modules/.pnpm/execa@6.1.0/node_modules/execa/index.js:193:17)
    at Object.execaCommandSync (/Users/liuqinghua/lqh/island.js/node_modules/.pnpm/execa@6.1.0/node_modules/execa/index.js:234:9)
    at null.prepareE2E (/Users/liuqinghua/lqh/island.js/scripts/prepare-e2e.cts:32:9) {
  shortMessage: 'Command failed with exit code 1: npm i --registry=https://registry.npmmirror.com/',
  command: 'npm i --registry=https://registry.npmmirror.com/',
  escapedCommand: 'npm i "--registry=https://registry.npmmirror.com/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Process from config.webServer was not able to start. Exit code: 1
```

### Reproduction

Run the command `npm run e2e:test`

### Expected behavior

Run correctly

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 156.31 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Safari: 16.0
```

### Validations

- [X] Read the [docs](https://island.sanyuan0704.top)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by liuqh0609** [comment]
#68
